version: 0.2

phases:
  install:
    commands:
      - printenv
      - cat .git/config

  pre_build:
    commands:
       - echo 00000000
       - git branch -a --contains HEAD
       - echo 11111111

  build:
    commands:
       - echo 2222222

artifacts:
  files:
    - '**/*'

