version: 0.2

phases:
  install:
    commands:
      - printenv
      - cat .git/config
      - git log --oneline

  pre_build:
    commands:
       - echo 0000000
       - git branch -a --contains HEAD
       - echo 1111111

  build:
    commands:
       - echo 222222

artifacts:
  files:
    - '**/*'

